name: Build and Release

on:
  push:
    branches:
      - main  # 仅 main 分支推送触发
  pull_request:
  workflow_dispatch:  # 允许手动触发
  release:
    types: [created]  # 当创建 Release 时自动触发

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64, arm, mips, mipsle, mips64, mips64le]
        exclude:
          - goos: darwin
            goarch: mips
          - goos: darwin
            goarch: mips64
          - goos: darwin
            goarch: mipsle
          - goos: darwin
            goarch: mips64le
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Go 环境
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: 编译 CNS
        run: |
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o CNS-${{ matrix.goos }}-${{ matrix.goarch }}
          ls -lh CNS-${{ matrix.goos }}-${{ matrix.goarch }}

      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: CNS-${{ matrix.goos }}-${{ matrix.goarch }}
          path: CNS-${{ matrix.goos }}-${{ matrix.goarch }}

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 下载所有构建产物
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: 发布 Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
