name: Build and Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version tag, e.g. v6.0.0'
        required: true
        default: 'v6.0.0'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # Darwin：仅支持 amd64 和 arm64
          - goos: darwin
            goarch: amd64
          - goos: darwin
            goarch: arm64
          # FreeBSD：支持 386 和 amd64
          - goos: freebsd
            goarch: 386
          - goos: freebsd
            goarch: amd64
          # Linux：支持多种架构
          - goos: linux
            goarch: 386
          - goos: linux
            goarch: amd64
          - goos: linux
            goarch: arm
          - goos: linux
            goarch: arm64
          - goos: linux
            goarch: mips
          - goos: linux
            goarch: mipsle
          - goos: linux
            goarch: mips64
          - goos: linux
            goarch: mips64le
          # Windows：支持 386 和 amd64
          - goos: windows
            goarch: 386
          - goos: windows
            goarch: amd64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: false

      - name: Build binaries with optimization
        run: |
          echo "Building for ${{ matrix.goos }}/${{ matrix.goarch }}"
          CGO_ENABLED=0 GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} \
            go build -trimpath -ldflags="-s -w -X main.Version=${{ github.event.inputs.version }}" \
            -o CNS-${{ matrix.goos }}-${{ matrix.goarch }}
          ls -lh CNS-${{ matrix.goos }}-${{ matrix.goarch }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: CNS-${{ matrix.goos }}-${{ matrix.goarch }}
          path: CNS-${{ matrix.goos }}-${{ matrix.goarch }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code for tag creation
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create tag if not exists
        run: |
          git fetch --tags
          if git rev-parse "${{ github.event.inputs.version }}" >/dev/null 2>&1; then
            echo "Tag ${{ github.event.inputs.version }} already exists"
          else
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git tag ${{ github.event.inputs.version }}
            git push origin ${{ github.event.inputs.version }}
          fi

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version }}
          files: artifacts/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
